### ISSUE TITLE
Determine menswear

### ISSUE THREAD

**Issue by huetingj** [huetingj/Wedding-planning#20]
- [x] Where to rent tuxes 
- [ ] Inform groomsmen
- [ ] Chad to work through other details: bow tie, ties, socks, belt, etc.

**Comment by chadfranklin** [comment]
$110 with Black Tux. Probably go with them since Matt and Caldwell are already in their system.

Remaining Questions:
- Rent only suit? What about shirt, shoes, tie?
- Any cheap options for buying tux for me? Rent will be about $200.
